---

# Ldap connections options (see)
ldap3:

  server:
    host: 'localhost'
    port: 389
    use_ssl: False
    get_info: ALL

  connection:
    user: 'cn=Directory Manager'
    password: 'azerty'

  search:
    - search_base: 'cn=monitor'
      search_scope: 'BASE'
      search_filter: '(objectclass=*)'
      attributes: '*'

# Flask (web server) options
flask:
  app:
    port: 9325
    host: 'localhost'
    debug: True


prometheus:
  metrics:
    - name: 'cn=monitor'
      mono_values:
        counters_help_label: "Compteur depuis le monitoring général"
        counters:
        - 'bytessent'
        - 'entriessent'
        - 'opscompleted'
        - 'opsinitiated'
        - 'totalconnections'
        
        gauges_help_label: "Jauges depuis le monitoring général"
        gauges:
        - 'cache-avail-bytes'
        - 'connectionpeak'
        - 'currentconnections'
        - 'currentpsearches'
        - 'dtablesize'
        - 'heapmaxhighhits'
        - 'heapmaxlowhits'
        - 'nbackends'
        - 'readwaiters'
        - 'request-que-backlog'
        - 'threads'
